server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /situacao-juridica/ {
        alias /usr/share/nginx/html/;
        try_files $uri$is_args$args /index.html;
    }

    location /assets/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
