quarkus.http.port=8085

quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=postgresql://localhost:5432/cerurbpro
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

quarkus.hibernate-orm.packages=br.com.foxinline.domain.model

# Desativa todos os DevServices que tentam subir containers
quarkus.devservices.enabled=false

quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.format-sql=false


# Auditoria
auditoria-api/mp-rest/url=http://localhost:9191
auditoria-api/mp-rest/scope=javax.inject.Singleton
auditoria-api/mp-rest/connectTimeout=5000
auditoria-api/mp-rest/readTimeout=10000

# Permite teste com o vue-teste
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,http://localhost:4175,https://cerurb-vue.foxinline.com/
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS