server {
    listen 80;

    # Define a raiz de onde o Nginx irá procurar os arquivos (dentro do container)
    root /usr/share/nginx/html;
    index index.html;

    # O prefixo '/estado' é usado pelo proxy externo e pelo build do Vite (base).
    # Precisamos remover este prefixo internamente no Nginx antes de procurar os arquivos.
    location /estado/ {
        alias /usr/share/nginx/html/;
        try_files $uri$is_args$args /index.html;
    }

    # Esta localização é necessária para o Microfrontend/Module Federation.
    location /assets/ {
        try_files $uri =404;
    }

    # Regra de fallback para a rota raiz (caso o proxy externo use a raiz)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
