server {
    listen 80;
    
    # Define a raiz de onde o Nginx irá procurar os arquivos (dentro do container)
    root /usr/share/nginx/html; 
    index index.html;

    # O prefixo '/tipo-comodo' é usado pelo proxy externo e pelo build do Vite (base).
    # Precisamos remover este prefixo internamente no Nginx antes de procurar os arquivos.
    location /tipo-comodo/ {
        # Tenta servir o arquivo estático, procurando na raiz do contêiner.
        # $uri = /tipo-comodo/assets/hostInit-lMk76T-n.js
        # O 'alias' remove o prefixo /tipo-comodo/ para que o Nginx procure 
        # em /usr/share/nginx/html/assets/hostInit-lMk76T-n.js
        alias /usr/share/nginx/html/;
        
        # Regra de fallback: Se não for um arquivo estático, retorna o index.html
        # É crucial para o roteamento do Vue/Module Federation.
        try_files $uri$is_args$args /index.html;
    }

    # Esta localização é necessária para o Microfrontend/Module Federation. 
    # Ela lida com a requisição direta de assets.
    location /assets/ {
        # Serve os assets estáticos
        try_files $uri =404;
    }
    
    # Regra de fallback para a rota raiz (caso o proxy externo use a raiz)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
